加载数据集

In [1]:
from keras.datasets import mnist

(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [5]:
print(train_images.shape)
print(len(train_labels))
train_labels

(60000, 28, 28)
60000


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

网络架构

In [6]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


#### 编译步骤

要想训练网络，我们还需要选择编译（compile）步骤的三个参数。
* 损失函数（loss function）：网络如何衡量在训练数据上的性能，即网络如何朝着正确的方向前进。
* 优化器（optimizer）：基于训练数据和损失函数来更新网络的机制。
* 在训练和测试过程中需要监控的指标（metric）：本例只关心精度，即正确分类的图像所占的比例。

In [8]:
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

#### 准备图像数据

在开始训练之前，我们将对数据进行预处理，将其变换为网络要求的形状，并缩放到所
有值都在[0, 1] 区间。比如，之前训练图像保存在一个uint8 类型的数组中，其形状为
(60000, 28, 28)，取值区间为[0, 255]。我们需要将其变换为一个float32 数组，其形
状为(60000, 28 * 28)，取值范围为0~1。



In [9]:
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32') / 255

准备标签

In [10]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

在训练数据上拟合（fit)模型

In [11]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 4s 62us/step - loss: 0.2551 - acc: 0.9260
Epoch 2/5
60000/60000 [==============================] - 3s 52us/step - loss: 0.1036 - acc: 0.9691
Epoch 3/5
60000/60000 [==============================] - ETA: 0s - loss: 0.0687 - acc: 0.979 - 3s 55us/step - loss: 0.0687 - acc: 0.9795
Epoch 4/5
60000/60000 [==============================] - 3s 53us/step - loss: 0.0505 - acc: 0.9850
Epoch 5/5
60000/60000 [==============================] - 3s 53us/step - loss: 0.0375 - acc: 0.9887


在测试集上检查一下

In [12]:
test_loss,test_acc = network.evaluate(test_images,test_labels)
print('test_acc:',test_acc)

10000/10000 [==============================] - 0s 24us/step
test_acc: 0.9793


In [13]:
import numpy as np

x = np.array(12)
x,x.ndim

(array(12), 0)

In [14]:
x = np.array([12,3,6,14,7])
x,x.ndim

(array([12,  3,  6, 14,  7]), 1)

In [15]:
x = np.array([[5,18,2,34,0],
              [6,79,3,35,1],
              [7,80,4,36,2]
             ])
x.ndim

2

In [16]:
x = np.array([[[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],
                [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]],
                [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]]])
x.ndim

3

In [17]:
x.shape

(3, 3, 5)

In [18]:
train_images.ndim

2